### ISSUE TITLE
How to run the code without docker?

### ISSUE THREAD

**Issue by xl-zhu** [iseekwonderful/HPA-singlecell-2nd-dual-head-pipeline#3]
I am interested in this method, but I have been unable to run your code, mainly due to the lack of configuration files.
I am not familiar with Docker, may I ask if there will be the file **train.sh** after Docker is installed? The code you provided does not seem to contain the **train.sh** file in readerme.

**Comment by evan-wehi** [comment]
#1

**Comment by xl-zhu** [comment]
I didn't pay attention to the question you ended earlier, thank you very much for your answer
